### PR TITLE
Make preview work and add onClickVideoFrame callback

### PR DESCRIPTION
**Pull request by tachang**
Kind of dirty but figured I'd create a PR.

### CODE REVIEW

**Comment by tachang** [comment]
The Toast is the same as when you did it? No?

**Comment by tachang** [comment]
It is in the sample code.

**Comment by afollestad** [comment]
screen shot 2016-12-27 at 3 25 19 pm

**Comment by tachang** [comment]
What I meant was the sample has Toasts already so I just kept it consistent.

**Comment by afollestad** [comment]
You're right, thanks

**Pull request merged**
