### PR TITLE
Add onStarted(EasyVideoPlayer) and onPaused(EasyVideoPlayer) methods …

### PR DESCRIPTION
**Pull request by franciscofranco**
…to let the subscriber know about these events

Signed-off-by: Francisco Franco <franciscofranco.1990@gmail.com>

### CODE REVIEW

**Comment by franciscofranco** [comment]
Ugh, I don't know why these pull-request commits are "merged", sorry. I haven't tested this code so don't merge & publish without making sure it's all fine and dandy.

**Comment by afollestad** [comment]
No worries, thanks!

**Comment by afollestad** [comment]
@franciscofranco I actually haven't had enough time to look at this in detail yet, but I noticed the `fullscreenListener` doesn't actually get defined :wink:

**Comment by afollestad** [comment]
Reverted to 0.2.8 for now

**Comment by franciscofranco** [comment]
Oh you wanted a listener? I made it automatic either if you touch the clickFrame or you toggle Play/Pause.

**Comment by afollestad** [comment]
Oh no, I just mean there's a variable being used in the PR that doesn't actually exist

**Comment by franciscofranco** [comment]
I'm retarded. Pushing a fix.

**Pull request merged**
